#!/usr/bin/env zsh
# -*- mode: Shell-script ;-*-

setopt transient_rprompt

local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%} )"

#
_prompt_jobs() {
    local jobs_status
    jobs_status=("")
    [[ $(jobs -l | wc -l) -gt 0 ]] && jobs_status+="%{%F{cyan}%}⚙"
    echo -n "$jobs_status"
}

function _prompt_pwd {
  setopt localoptions extendedglob
  # adapted from gh:sorin-ionescu/prezto
  local pwd="${PWD/#$HOME/~}"

  if [[ "$pwd" == (#m)[/~] ]] {
    print -n "$MATCH"
    unset MATCH
  } else {
    print -n "${${${${(@j:/:M)${(@s:/:)pwd}##.#?}:h}%/}//\%/%%}/${${pwd:t}//\%/%%}"
  }
}

_prompt_where() {

  local grey="%{[38;5;246m%}"
  local orange="%{[38;5;208m%}"
  local blue="%{[38;5;45m%}"
  local yellow="%{[38;5;220m%}"
  local cagein=""

  print -n "%{%f%b%k%}"
  if [[ -n $SSH_CLIENT || -n $REMOTEHOST || $USER != $LOGNAME || $(id -u) -eq 0 ]] {
    print -n "%{$fg[blue]%}%n%f@%{${grey}%}%m%f"
  } else {
    print -n "%{${grey}%}λ%f"
  }

  if [[ "$UNDER_JHBUILD" = "true" ]] {
    cagein=${blue}
  } elif [[ -n ${VIRTUAL_ENV} ]] {
    cagein=${yellow}
  } else {
    cagein=${gray}
  }

  print -n " $(_prompt_pwd) %(!.%F{red}.%{${cagein}%})→%f"
}

setopt PROMPT_SUBST
RPROMPT='${return_code}$(_prompt_jobs)'
if (( ${+commands[git-radar]} )) {
  RPROMPT="$RPROMPT\$(git-radar --zsh --fetch)"
}

PROMPT='$(_prompt_where) '
