#!/usr/bin/env zsh
# colour ls
#eval `dircolors`
export LS_OPTIONS="-hF --color=auto"

#ENVIROMENT
#use the full powers
if [[ -d /sys/devices/system/cpu ]]; then
  export MAKEFLAGS="-j`ls -1F /sys/devices/system/cpu | grep "\/" | wc -l`"
fi

#GtkFileChooser needs be thought to behave
export GTK_DEFAULT_FILECHOOSER_DIR=$HOME

#editor setup
alias mvim=gvim
