#!/usr/bin/env zsh

if [ ! -n "${ZPLUGDIR+1}" ]; then
  ZPLUGDIR=$HOME/.zsh/plugins
  source $ZPLUGDIR/emacsclient/common.zsh
fi

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 FILE" >&2
  exit 1
fi

if [ "$(emacs_server_gui)" = "t" ]; then
    emacs_set_focus
    test "$#" -ne "0" && emacsclient -e "(find-file \"/sudo::$1\")"
    return
fi

# try switching to the frame in case it is just minimized
# will start a server if not running
test "$(emacs_visible_frames)" -eq "1" && emacs_set_focus

# now we are guaranteed to have a server running, check
# if we need to create a frame (daemon with no frames
# visible count 1)
if [ "$(emacs_visible_frames)" -lt  "2" ]; then
    emacsclient -e "(find-file \"/sudo::$1\")" && emacs_set_focus
else
    emacs_set_focus
    emacsclient -e "(find-file \"/sudo::$1\")"
fi
